class Solution {
    public:
        vector<int> gcdValues(vector<int>& nums, vector<long long>& queries) {
                int maxVal = *max_element(nums.begin(), nums.end());
                        
                                // freq[v] = count of nums equal to v
                                        vector<long long> freq(maxVal + 1, 0);
                                                for (int x : nums) freq[x]++;
                                                        
                                                                // cntDiv[g] = count of numbers in nums divisible by g
                                                                        vector<long long> cntDiv(maxVal + 1, 0);
                                                                                for (int g = 1; g <= maxVal; g++)
                                                                                            for (int mult = g; mult <= maxVal; mult += g)
                                                                                                            cntDiv[g] += freq[mult];
                                                                                                                    
                                                                                                                            // gcdCnt[g] = number of pairs with GCD exactly g
                                                                                                                                    // Start with pairs where both divisible by g: C(cntDiv[g], 2)
                                                                                                                                            // Then subtract overcounts using inclusion-exclusion (Mobius)
                                                                                                                                                    vector<long long> gcdCnt(maxVal + 1, 0);
                                                                                                                                                            for (int g = maxVal; g >= 1; g--) {
                                                                                                                                                                        long long c = cntDiv[g];
                                                                                                                                                                                    gcdCnt[g] = c * (c - 1) / 2;
                                                                                                                                                                                                // Subtract pairs with GCD = 2g, 3g, ...
                                                                                                                                                                                                            for (int mult = 2 * g; mult <= maxVal; mult += g)
                                                                                                                                                                                                                            gcdCnt[g] -= gcdCnt[mult];
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                    // Build prefix sum for binary search
                                                                                                                                                                                                                                                            vector<long long> prefix(maxVal + 2, 0);
                                                                                                                                                                                                                                                                    for (int g = 1; g <= maxVal; g++)
                                                                                                                                                                                                                                                                                prefix[g] = prefix[g - 1] + gcdCnt[g];
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                // Answer each query with binary search
                                                                                                                                                                                                                                                                                                        vector<int> ans;
                                                                                                                                                                                                                                                                                                                for (long long q : queries) {
                                                                                                                                                                                                                                                                                                                            // Find smallest g such that prefix[g] > q
                                                                                                                                                                                                                                                                                                                                        int lo = 1, hi = maxVal, res = maxVal;
                                                                                                                                                                                                                                                                                                                                                    while (lo <= hi) {
                                                                                                                                                                                                                                                                                                                                                                    int mid = (lo + hi) / 2;
                                                                                                                                                                                                                                                                                                                                                                                    if (prefix[mid] > q) {
                                                                                                                                                                                                                                                                                                                                                                                                        res = mid;
                                                                                                                                                                                                                                                                                                                                                                                                                            hi = mid - 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                lo = mid + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ans.push_back(res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
